/**Mock data for the items used in the website */
const init_data = [
  {
    id: "item-101",
    name: "Dell Vostro 3910 Desktop PC",
    type: "desktop",
    description: {
      Processor: "Core i7",
      Memory: "8gb RAM",
      Storage: "1000gb",
      OS: "Windows 11",
    },
    price: "17000.00",
    Count: 1,
    imageLocation: "./images/dell-hot.jpg",
  },
  {
    id: "item-102",
    name: "Lenovo ThinkCentre Neo 50T G3 Desktop PC",
    type: "desktop",
    description: {
      Processor: "Core i7",
      Memory: "8gb RAM",
      Storage: "1000gb",
      OS: "Windows 11",
    },
    price: "17000.00",
    Count: 1,
    imageLocation: "./images/lenovo.webp",
  },
  {
    id: "item-103",
    name: "HP 290 G4 Desktop PC",
    type: "desktop",
    description: {
      Processor: "Core i7",
      Memory: "8gb RAM",
      Storage: "1000gb",
      OS: "Windows 11",
    },
    price: "17000.00",
    Count: 1,
    imageLocation: "./images/hp.webp",
  },
  {
    id: "item-104",
    name: "Volkano Bluetooth 5.0 Headphones B39",
    type: "accessory",
    description: {
      Connection: "Bluetooth 5.0",
      Microphone: "Yes",
      Sensitivity: "70dB",
      Frequency: "20Hz ~ 20KHz",
    },
    price: "199.00",
    Count: 1,
    imageLocation: "./images/heads.webp",
  },
  {
    id: "item-105",
    name: "Logitech G102 USB Gaming Mouse",
    type: "accessory",
    description: {
      "Color(s)": "RGB, black",
      OS: "Windows, 7 and later, MacOs, Linux",
      Connection: "Wired",
      Responsiveness: "200 - 8,000 DPI",
    },
    price: "295.00",
    Count: 1,
    imageLocation: "./images/mouse.webp",
  },
  {
    id: "item-106",
    name: "Alcatroz Xplorer K330 Keyboard",
    type: "accessory",
    description: {
      "Color(s)": "black",
      OS: "Windows, 7 and later, MacOs, Linux",
      Connection: "Wired",
      keys: "104",
    },
    price: "89.00",
    Count: 1,
    imageLocation: "./images/keboard.webp",
  },
  {
    id: "item-107",
    name: "DeepCool Smarter U-ATX Chassis",
    type: "component",
    description: "",
    price: "459.00",
    Count: 1,
    imageLocation: "./images/chassis.webp",
  },
  {
    id: "item-108",
    name: "ASUS Prime H610M-E Intel LGA 1700 Motherboard",
    type: "component",
    description: "",
    price: "1399.00",
    Count: 1,
    imageLocation: "./images/motherboard.webp",
  },
  {
    id: "item-109",
    name: "WD Blue 1TB harddrive",
    type: "component",
    description: "",
    price: "459.00",
    Count: 1,
    imageLocation: "./images/harddrive.jpg",
  },
  {
    id: "item-110",
    name: "Intel Core i7 Processor",
    type: "component",
    description: "",
    price: "5000.00",
    Count: 1,
    imageLocation: "./images/cpu-icon.png",
  },
];
